name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20 # Specify the Node.js version you need

    - name: Install dependencies
      run: npm ci

    - name: Start Next.js development server
      run: npm run dev &
      env:
        CI: true

    - name: Run Cypress tests
      run: npx cypress run --env CI=true