name: K6 Load CI test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs: 
  build:
    name: K6 Load Smoke test
    runs-on: ubuntu-latest
    steps:
    - name: step 1 - checkout
      uses: actions/checkout@v4

    - name: step 2 - run k6 load test
      uses: grafana/k6-action@v0.3.1
      with:
        filename: k6-tests/load_ci_test.js

    - run: ls & mkdir report & mv index.html report

    - name: step 3 - upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Load Smoke Test report
        path: report

    - name: step 4 - publish report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: report



